apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudtest
  labels:
    app: cloudtest
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: cloudtest
      
  template:
    metadata:
      labels:
        app: cloudtest
        tier: cloudtest
    spec:
      containers:
        - name: cloudtest
          image: erandiranaweera/erandicw:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
            name: cloudtest


---
apiVersion: v1
kind: Service
metadata:
  name: cloudtest
  labels:
    app: cloudtest
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: cloudtest
    tier: cloudtest
  type: LoadBalancer
